### ISSUE TITLE
samples maybe need some update

### ISSUE THREAD

**Issue by moketao** [matigramirez/Parsec#10]
https://github.com/matigramirez/Parsec/blob/0e1f5e608cb302a76b23607b1efd693dec56fda6/samples/ani/Parsec.Samples.Ani/Program.cs#L23

Console.WriteLine($"{{{aniStep.ParentBoneIndex}  {aniStep.Rotations.Count}  {aniStep.Translations.Count}}}");

**Comment by moketao** [comment]
@matigramirez  By the way,  Nice work

**Comment by matigramirez** [comment]
Thank you for bringing this to my attention @moketao. You're right, I updated the ani class some hours ago and I forgot to update the sample, it should be fixed now. I also need to update the readme.
