### ISSUE TITLE
Support for SEFF

### ISSUE THREAD

**Issue by DagoDagorath** [matigramirez/Parsec#19]
Add support for `*.seff` files
[Castors notes](https://www.elitepvpers.com/forum/shaiya-pserver-guides-releases/2082477-re-release-weapon-glow-effect.html#post18458035) & [seff.zip](https://github.com/matigramirez/Parsec/files/7583913/seff.zip)
Main file that is of interest is `weapon.seff` however, other ones that can be found in standard client can be handy as well for some in-game features. Current theoretical structure according to Castor:
```C#
> // effect info
struct EffectInfo {
	long	u1;
	float	f1;
	long	u2, u3, u4;
	float	f2;
	String	name;	// wchar_t array, length prefixed, name of a .DDS file
	long	rgb[6];
	float	x, y, z;
	long	u5;
};
struct Effect {
	long	ident;	// index in .seff file
	long	count;	// number of EffectInfo to follow
	EffectInfo* effi;
};
// content of a .seff file
struct EffectsSet {
	long	u[4];	// unknown
	long	count;	// number of Effect to follow
	Effect* effects;
};
```

**Comment by matigramirez** [comment]
Added on [7c9bf772c8a8d98d1c1e0e2646e97eefb3d2529e](https://github.com/matigramirez/Parsec/commit/7c9bf772c8a8d98d1c1e0e2646e97eefb3d2529e)
