### ISSUE TITLE
*.dg file support

### ISSUE THREAD

**Issue by DagoDagorath** [matigramirez/Parsec#23]
Open world maps have *.wld extension, however dungeon type maps have *.dg and their structure, according to Castor is a set of *.SMOD items.
[guildanteroom_d.zip](https://github.com/matigramirez/Parsec/files/7651727/guildanteroom_d.zip)
In ShStudio it's possible to go quite in-depth
![image](https://user-images.githubusercontent.com/39481492/144656588-bbe3c844-9f0c-4007-abec-e08f10281407.png)
possibly related to understanding *.SMOD better.

Some of the *.dg files have an extra file with same name but *.dg_pv extension instead (structure seems to be somewhat similar).
[dg_pv.zip](https://github.com/matigramirez/Parsec/files/7651752/dg_pv.zip)

**Comment by matigramirez** [comment]
Added on [a4b3d9c](https://github.com/matigramirez/Parsec/commit/a4b3d9c231d9b6c224806cfb4701cf672016aded)
