### ISSUE TITLE
*.zon file support

### ISSUE THREAD

**Issue by DagoDagorath** [matigramirez/Parsec#24]
There is just a single *.zon file in client (6.3) and it's responsible for the safe zones on client side? (Possibly communicating with *.svmap on server side) However in a test configuration I have no entries for map 47 (jungle) on svmap and having entries here denies skills/attacks in-game.
[TacticsZone.zip](https://github.com/matigramirez/Parsec/files/7651811/TacticsZone.zip)
Structure is unknown for now, however possibly it's similar to *.svmap where information can be entered about safe zones.
ShStudio is capable of previewing it to a certain degree:
![image](https://user-images.githubusercontent.com/39481492/144658800-671c074a-6280-46b0-8f0e-eac7ce92c116.png)

**Comment by matigramirez** [comment]
Support for `zon` added on [6505d05](https://github.com/matigramirez/Parsec/commit/6505d05443f7d4aa82bead1688b748043a67e269)

Structure:
```cpp
struct Zon {
  int format;
  int recordCount;
  Record records[recordCount];
}

struct Record {
  byte index;
  byte P1;
  
  // START : only if format > 2
  byte P2;
  // END: only if format > 2

  Vector3 coordinates1;  // y coordinate is always 0.0 and I don't think it's used by the client at all
  Vector3 coordinates2;  // y coordinate is always 0.0 and I don't think it's used by the client at all

  // START : only if format > 2
  Vector3 coordinates3;  // y coordinate is always 0.0 and I don't think it's used by the client at all
  Vector3 coordinates4;  // y coordinate is always 0.0 and I don't think it's used by the client at all
  float unknown1; // always 0.0 afaik
  float unknown2; // always 0.0 afaik
  // END : only if format > 2

  short mapId;
  String description; // it doesn't include the \0 terminator that is present in other formats
}

struct Vector3 {
  float x, y, z;
}

struct String {
  int length;
  char str[length];
}
```
