### ISSUE TITLE
SvMap: portal Faction is parsed incorrect

### ISSUE THREAD

**Issue by aosyatnik** [matigramirez/Parsec#29]
**Describe the bug**
There is implementation of faction for SvMap:
```
public class Portal : IBinary
{
        public Vector3 Position { get; set; }
        public FactionInt Faction { get; set; }
        ...
}

public enum FactionInt
{
        Light,
        Fury,
        Any
}
```

The problem is that for portals Light has value 1 and Fury has value 2. And if value is > 2, then portal is activated with boss death. 

**Expected behavior**
Rethink how portal faction is parsed.

**Screenshots**
Can be easily checked for map № 2 (start Fury map):
![image](https://user-images.githubusercontent.com/8158404/165263165-e138e033-921d-430e-ab8f-8338e6dfa1ef.png)
Or with map № 50 (GBR map), portal is opened on boss death:
![image](https://user-images.githubusercontent.com/8158404/165263627-d9dc6fd9-d7aa-48cd-87ad-eb7f2ab495e2.png)

**Comment by l3owie** [comment]
that id is also used by the invasion system. the client expects certain ids to be sent in packets for the notices (see sysmsg-uni.txt) to work correctly. here's the Obelisk.ini configuration for reference.

`ini
;Deep Desert
[Portal_001, (0, 1010) ]
    [light] = (0,Obelisk_001),(0,Obelisk_002),(0,Obelisk_005)
    
[Portal_002, (0, 1020) ]
    [fury]  = (0,Obelisk_003),(0,Obelisk_004),(0,Obelisk_005)    

;Stable Erde
[Portal_003, (0, 1011) ]
    [light] = (0,Obelisk_001),(0,Obelisk_005),(0,Obelisk_006)
    
[Portal_004, (0, 1021) ]
    [fury]  = (0,Obelisk_004),(0,Obelisk_005),(0,Obelisk_007)

;Kanos Illium
[Portal_001, (70, 1060) ]
    [light] = (70,Obelisk_001),(70,Obelisk_002),(70,Obelisk_003)
    
[Portal_002, (70, 1061) ]
    [fury]  = (70,Obelisk_001),(70,Obelisk_002),(70,Obelisk_003) 
`

i think it should just be an integer number without any kind of enumeration.

**Comment by matigramirez** [comment]
You're right Anna. Thank you for your input. This was fixed in Bowie's latest PR which he linked above.
