### ISSUE TITLE
NpcQuest: reward item vs farm item

### ISSUE THREAD

**Issue by aosyatnik** [matigramirez/Parsec#32]
**Describe the bug**
I think property `RewardItems` (Quest.cs) is called incorrect. I suggest renaming it into `FarmItems`. As revard items are part of `Results` property.

**To Reproduce**
This can be easily checked with quest № 3401. Quest asks player to buy 10 Pomegranates, which is item (25, 4). And player will get back 20 Pomegranates and Exp and Money:
![image](https://user-images.githubusercontent.com/8158404/165899926-31e26c78-4353-4266-ac74-7a20b355119f.png)

**Expected behavior**
I can rename `RewardItems` into `FarmItems`. Unless it's different in other eps.

**Comment by matigramirez** [comment]
Fixed on #35
