### ISSUE TITLE
When exporting to csv it breaks the accents

### ISSUE THREAD

**Issue by Gexur** [matigramirez/Parsec#42]
**Describe the bug**
When exporting to csv it breaks the accents

**To Reproduce**
Export it as csv

**Expected behavior**
See the accents in the exported csv

**Screnshoot**
![image](https://user-images.githubusercontent.com/100322127/229539206-8cb213cb-0756-4a62-b9be-7efea5409bfd.png)

**Additional context**
I tried adding this line of code but it doesn't work
```
var encoder = Encoding.GetEncoding("iso-8859-1");
using var writer = new StreamWriter(outputPath, false, encoder);
```

**Comment by matigramirez** [comment]
This happens because the strings are being read with windows-1252 encoding, so no matter how you open the csv files, those characters will already be missing. When I get the chance I'll implement some sort of encoding selection

**Comment by matigramirez** [comment]
@Gexur it's been a while, but with the latest release this issue is now fixed, you can read/write the file using a specific encoding. If I'm not mistaken, the screenshot you shared is from a spanish Item.SData, you can do the following:

```cs
// Write the csv file
var windows1252Encoding = CodePagesEncodingProvider.Instance.GetEncoding(1252);
var item = ParsecReader.FromFile<Item>("Item.SData", Episode.Ep6, windows1252Encoding);
item.WriteCsv("Item.csv", windows1252Encoding);
```

Once you're done with the csv file:
```cs
// Read item from csv
var itemFromCsv = Item.FromCsv("Item.csv", windows1252Encoding);
itemFromCsv.WriteEncrypted("Item_new.SData");
```
