### ISSUE TITLE
Data: write sah on file removal

### ISSUE THREAD

**Issue by sdev23** [matigramirez/Parsec#49]
when i did this in my app, i was expecting `data.sah` to be changed on-disk, but it wasn't.

```csharp
var data = new Parsec.Shaiya.Data.Data("data.sah");
data.RemoveFilesFromLst("delete.lst");
```

**Comment by matigramirez** [comment]
The remove methods don't overwrite the existing `data.sah` file on disk because many files could be added/removed within a program, which would result in writing the file multiple times. The only time the `.sah` file gets written explicitly is when using the `DataPatcher` class methods.
`RemoveFilesFromLst` in particular could potentially do a single write when completed, but I gotta give it some thought

**Comment by sdev23** [comment]
understood. thanks for responding. perhaps a note in the description for `RemoveFile` and `RemoveFilesFromLst` would do. i took the comments too literally, but that's on me.

**Comment by sdev23** [comment]
understood. thanks for explaining. how do you feel about this?

```csharp
/// <summary>
/// Removes a file from both the sah and saf files
/// </summary>
/// <param name="path"></param>
/// <param name="writeSahFlag">If true, writes the sah file on-disk</param>
public void RemoveFile(string path, bool writeSahFlag = false)
{
    if (!FileIndex.TryGetValue(path, out var file))
        return;

    // Remove file from sah
    Sah.FileCount--;
    file.ParentFolder.Files.Remove(file);
    FileIndex.Remove(path);

    if (writeSahFlag)
    {
        FileHelper.DeleteFile(Sah.Path);
        Sah.Write(Sah.Path);
    }

    // Clear bytes on saf
    Saf.ClearBytes(file.Offset, file.Length);
}

/// <summary>
/// Removes data files from a deletion list (delete.lst)
/// </summary>
/// <param name="lstPath">Path to delete.lst file</param>
public void RemoveFilesFromLst(string lstPath)
{
    var filePaths = File.ReadAllLines(lstPath);

    foreach (var file in filePaths)
        RemoveFile(file);

    FileHelper.DeleteFile(Sah.Path);
    Sah.Write(Sah.Path);
}
```
